language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- export PATH=$PWD/node_modules/.bin:$PATH
- polylint
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: wP3Uchjq5Uxj0/RJ2db5RKeJzI/SEqxtjJv+r98pGGprKfNhbqpfKDRF8H9YZ8zSdbPXucPI9e7dgjZGWFcZx+s7cBWYYRxli1MSEu3+tsxO2gR2CxhBi6OqHdYkql0qQ6ggTpNBDblSGfWwUUNsZBnpYRYtjUpzMUo9luXCFamdvlS6yYvhrdbSJS5RBa+kmrq2SqH5lK6mzCPnsMcw/nVKMVwkI54veFvHGdhb7ZFJOdSIAxcNf+sLgDuCu2jG5alBJI2h8EWqxeT7l5KTKzVeq6ZiJbNdAljHBAbnUBj5jWnJ9Mo57ww3feJX34B6AYvhkOtRRtU+4jfWtjcJcb6giy+L0ykN8wdoihQQJesw2yOWNJxo9Gv4xTeyshL8K+2GZHmNGqh/X5q+rinHmxhVtuN7mScT898t8MFbQuM3izMk5LzryoVUKxXmOrukmpbDuEPb3mqrAH7PqCBFcw8XRGGdMt7gTJrmmG8fW38wBWSQaLGKUTbURW4IgbHyWa3d/83wLH2mrbBWvYe4++4tDHCNVjbst8bbvTgTugU5EZbP5V5jV5piYfq2GPtRiWyFofg3M3XRAXuGTSzWkLsCOf3BMIZzQoWkYE+gHSz6SoYjBOgyG56koiI/QVyXdWuVEbg/EDG9DIVD8HplygkUhpYAFuccuG89OfgU82g=
  - secure: 3tUnbxzzl+t2IvxcjTJ/XE/RjozzzZz/LsJxgK8CWGcIMUepYkbNDwlSRa88T/tr1N2Q5bGc0blqLYzPO31V2VwU2z8a7uJdv1MKp+z5vp9z9ifApxTe19LRM4jGEskMGxVadoV0iTjOepRRcE12TgSbc6xgg5OZrtfUv5riG9DJeq4RW4HdNCmMnMbvwjqODCSenv9bbcsxNDO6nPexY+R9MNiihFhkNUB8ubUQi4gzChqUzlgH4H6ODuZepYmAk2yVN8+ubhSknJ0huyRjnluswoyJWPsQBEuppYa9kEuKV/iswwQrmOm6Bb7wvdhOJfF0RURUpMj24wVfainTFJ5LCVYi1mFc0Ucizbn/M+MyVtuzh4HlH9X6s4hr4OXDIp/v6AxPU68FpcbtcGu1QN1hDdkeOyLBvV+7RfIimlnzgwETrsUV/o+QYx8eTefBVuaGA15tTiPTTtePKu9dhUsEG0pLYN17TcbJhKUyitnkg8gbb9fkYtnDgxkXja9crptplN4NqG+L4FWPnAtAn5YvfgE8iSprf5m1XSD2PzMgR2iicp/mqM5Lf/eHFmSw9d4YzUEoQ5MqQJ7b4YSejeAkpYjylt3McrE5guomwNOzGWb1XYnjZW/s2OpfYmsVyRhtca5bfxT/wbO+qfNVwib6DH5UEeKYkNPNY+QRsYg=
